# ${project['grace.app.name']}

This project is generated by Grace v${versions['grace.version']} and Groovy v${versions['groovy.version']}.

Profile: ${project['grace.app.name']}
Features: ${project['grace.app.features']}
Template: ${project['grace.app.template']}

## Versions

* Grace ${versions['grace.version']}
* Groovy ${versions['groovy.version']}
* Spring Boot ${versions['spring-boot.version']}
* Spring Framework ${versions['spring-framework.version']}
* Tomcat ${versions['tomcat.version']}

## Options

template = ${options['template']}
features = ${options['features']}
database = ${options['database']}
css = ${options['css']}
javascript = ${options['javascript']}
api = ${options['api']}
minimal = ${options['minimal']}