println 'Post Apply Application Template'

ant.sequential {

    file(name: 'Help.md', 
    '''# Help
Learn how to use Application Template to quick creaet your next Grace project.
''')

    git(init: '-q')
    git(add: '.')
    git(commit: "-m 'Generated by Grace ${project.graceVersion}'")

    run('tree . -L 2 --dirsfirst -C')

    say 'Done.'
}
